apiVersion: v1
kind: ConfigMap
metadata:
  name: eglas-config
  namespace: eglas
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://eglas-db-service.eglas.svc.cluster.local:5432/postgres
  SPRING_DATASOURCE_USERNAME: postgres

---

apiVersion: v1
kind: Secret
metadata:
  name: eglas-secret
  namespace: eglas
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: am92YW4xMjM=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eglas-deployment
  namespace: eglas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eglas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: eglas
    spec:
      containers:
        - name: eglas-app
          image: jovansimonoski/eglas_app:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: eglas-config
            - secretRef:
                name: eglas-secret

