apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eglas-db-pvc
  namespace: eglas
  labels:
    app: eglas-db
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
